services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: ["redis-server", "--appendonly", "yes"]
